import { Injectable } from '@angular/core';
import { Category } from '../model/category';

@Injectable({
  providedIn: 'root',
})
export class StoreService {
  public store: Category[] = [];

  constructor() {
    this.store = this.getStoreFromDb();
  }

  getStoreFromDb = () => {
    return [
      {
        id: 1,
        key: 'background',
        url: '/assets/img/FONDO.png',
        items: [
          { id: 1, url: 'assets/img/background/BASE.png' },
          { id: 2, url: 'assets/img/background/1.png' },
          { id: 3, url: 'assets/img/background/2.png' },
          { id: 4, url: 'assets/img/background/3.png' },
          { id: 5, url: 'assets/img/background/4.png' },
          { id: 6, url: 'assets/img/background/5.png' },
          { id: 7, url: 'assets/img/background/6.png' },
          { id: 8, url: 'assets/img/background/7.png' },
          { id: 9, url: 'assets/img/background/8.png' },
          { id: 10, url: 'assets/img/background/9.png' },
          { id: 11, url: 'assets/img/background/10.png' },
          { id: 12, url: 'assets/img/background/11.png' },
          { id: 13, url: 'assets/img/background/12.png' },
          { id: 14, url: 'assets/img/background/13.png' },
          { id: 15, url: 'assets/img/background/15.png' },
          { id: 16, url: 'assets/img/background/16.png' },
          { id: 17, url: 'assets/img/background/17.png' },
          { id: 18, url: 'assets/img/background/18.png' },
          { id: 19, url: 'assets/img/background/19.png' },
          { id: 20, url: 'assets/img/background/20.png' },
          { id: 21, url: 'assets/img/background/OUTERSPACE.png' },
        ],
      },
      {
        id: 2,
        key: 'body',
        url: '/assets/img/PLAYER.png',
        items: [
          { id: 1, url: 'assets/img/character/BASE.png' },
          { id: 2, url: 'assets/img/character/BLACK.png' },
          { id: 3, url: 'assets/img/character/BLUE.png' },
          { id: 4, url: 'assets/img/character/BROWN.png' },
          { id: 5, url: 'assets/img/character/CYAN.png' },
          { id: 6, url: 'assets/img/character/DARKGREEN.png' },
          { id: 7, url: 'assets/img/character/GREEN.png' },
          { id: 8, url: 'assets/img/character/ORANGE.png' },
          { id: 9, url: 'assets/img/character/PINK.png' },
          { id: 10, url: 'assets/img/character/PURPLE.png' },
          { id: 11, url: 'assets/img/character/RED.png' },
          { id: 12, url: 'assets/img/character/WHITE.png' },
          { id: 13, url: 'assets/img/character/YELLOW.png' },
        ],
      },
      {
        id: 3,
        key: 'hat',
        url: '/assets/img/HAT.png',
        items: [
          { id: 1, url: 'assets/img/background/BASE.png' },
          { id: 2, url: 'assets/img/hat/ALIEN.png' },
          { id: 3, url: 'assets/img/hat/ANTHENA.png' },
          { id: 4, url: 'assets/img/hat/ASTRO.png' },
          { id: 5, url: 'assets/img/hat/BAG.png' },
          { id: 6, url: 'assets/img/hat/BALLOON1.png' },
          { id: 7, url: 'assets/img/hat/BALLOON10.png' },
          { id: 8, url: 'assets/img/hat/BALLOON11.png' },
          { id: 9, url: 'assets/img/hat/BALLOON12.png' },
          { id: 10, url: 'assets/img/hat/BALLOON2.png' },
          { id: 11, url: 'assets/img/hat/BALLOON3.png' },
          { id: 12, url: 'assets/img/hat/BALLOON4.png' },
          { id: 13, url: 'assets/img/hat/BALLOON5.png' },
          { id: 14, url: 'assets/img/hat/BALLOON6.png' },
          { id: 15, url: 'assets/img/hat/BALLOON7.png' },
          { id: 16, url: 'assets/img/hat/BALLOON8.png' },
          { id: 17, url: 'assets/img/hat/BALLOON9.png' },
          { id: 18, url: 'assets/img/hat/BANANA.png' },
          { id: 19, url: 'assets/img/hat/BANDANA.png' },
          { id: 20, url: 'assets/img/hat/BAT.png' },
          { id: 21, url: 'assets/img/hat/BEANIE.png' },
          { id: 22, url: 'assets/img/hat/BEAR.png' },
          { id: 23, url: 'assets/img/hat/BERET.png' },
          { id: 24, url: 'assets/img/hat/BIRTHDAY.png' },
          { id: 25, url: 'assets/img/hat/BLACK.png' },
          { id: 26, url: 'assets/img/hat/BROWS.png' },
          { id: 27, url: 'assets/img/hat/CANE.png' },
          { id: 28, url: 'assets/img/hat/CAP.png' },
          { id: 29, url: 'assets/img/hat/CAPTAIN.png' },
          { id: 30, url: 'assets/img/hat/CAT.png' },
          { id: 31, url: 'assets/img/hat/CHEESE.png' },
          { id: 32, url: 'assets/img/hat/CHEF.png' },
          { id: 33, url: 'assets/img/hat/CHERRY.png' },
          { id: 34, url: 'assets/img/hat/COP.png' },
          { id: 35, url: 'assets/img/hat/COWBOY.png' },
          { id: 36, url: 'assets/img/hat/CREWMATE.png' },
          { id: 37, url: 'assets/img/hat/CREWMATE10.png' },
          { id: 38, url: 'assets/img/hat/CREWMATE11.png' },
          { id: 39, url: 'assets/img/hat/CREWMATE12.png' },
          { id: 40, url: 'assets/img/hat/CREWMATE2.png' },
          { id: 41, url: 'assets/img/hat/CREWMATE3.png' },
          { id: 42, url: 'assets/img/hat/CREWMATE4.png' },
          { id: 43, url: 'assets/img/hat/CREWMATE5.png' },
          { id: 44, url: 'assets/img/hat/CREWMATE6.png' },
          { id: 45, url: 'assets/img/hat/CREWMATE7.png' },
          { id: 46, url: 'assets/img/hat/CREWMATE8.png' },
          { id: 47, url: 'assets/img/hat/CREWMATE9.png' },
          { id: 48, url: 'assets/img/hat/CROWN.png' },
          { id: 49, url: 'assets/img/hat/CUERVO.png' },
          { id: 50, url: 'assets/img/hat/DEVIL.png' },
          { id: 51, url: 'assets/img/hat/DOCTOR.png' },
          { id: 52, url: 'assets/img/hat/DOUBLE.png' },
          { id: 53, url: 'assets/img/hat/DRAIN.png' },
          { id: 54, url: 'assets/img/hat/EGG.png' },
          { id: 55, url: 'assets/img/hat/ELMER.png' },
          { id: 56, url: 'assets/img/hat/EYE.png' },
          { id: 57, url: 'assets/img/hat/FEZ.png' },
          { id: 58, url: 'assets/img/hat/FLAMINGO.png' },
          { id: 59, url: 'assets/img/hat/FLOWER.png' },
          { id: 60, url: 'assets/img/hat/FLOWERPOT.png' },
          { id: 61, url: 'assets/img/hat/FREEZE.png' },
          { id: 62, url: 'assets/img/hat/GASMASK.png' },
          { id: 63, url: 'assets/img/hat/GOGGLES.png' },
          { id: 64, url: 'assets/img/hat/GOGGLES2.png' },
          { id: 65, url: 'assets/img/hat/GREEN.png' },
          { id: 66, url: 'assets/img/hat/HADES.png' },
          { id: 67, url: 'assets/img/hat/HALO.png' },
          { id: 68, url: 'assets/img/hat/HAWK.png' },
          { id: 69, url: 'assets/img/hat/HEADBAND.png' },
          { id: 70, url: 'assets/img/hat/HEADPHONES.png' },
          { id: 71, url: 'assets/img/hat/HELMET.png' },
          { id: 72, url: 'assets/img/hat/HERCULES.png' },
          { id: 73, url: 'assets/img/hat/HORNS.png' },
          { id: 74, url: 'assets/img/hat/JASON.png' },
          { id: 75, url: 'assets/img/hat/KNIFE.png' },
          { id: 76, url: 'assets/img/hat/LIGHTS.png' },
          { id: 77, url: 'assets/img/hat/LINK.png' },
          { id: 78, url: 'assets/img/hat/MADHATTER.png' },
          { id: 79, url: 'assets/img/hat/MASK.png' },
          { id: 80, url: 'assets/img/hat/MEGARA.png' },
          { id: 81, url: 'assets/img/hat/MILITARY.png' },
          { id: 82, url: 'assets/img/hat/MINER.png' },
          { id: 83, url: 'assets/img/hat/MORTY.png' },
          { id: 84, url: 'assets/img/hat/NEST.png' },
          { id: 85, url: 'assets/img/hat/NINJA.png' },
          { id: 86, url: 'assets/img/hat/PAPER.png' },
          { id: 87, url: 'assets/img/hat/PAPERHAT.png' },
          { id: 88, url: 'assets/img/hat/PARTY.png' },
          { id: 89, url: 'assets/img/hat/PILOT.png' },
          { id: 90, url: 'assets/img/hat/PIRATE.png' },
          { id: 91, url: 'assets/img/hat/PLANT.png' },
          { id: 92, url: 'assets/img/hat/POLICE.png' },
          { id: 93, url: 'assets/img/hat/POMPADOUR.png' },
          { id: 94, url: 'assets/img/hat/POSTIT.png' },
          { id: 95, url: 'assets/img/hat/PRESENT.png' },
          { id: 96, url: 'assets/img/hat/REDQUEEN.png' },
          { id: 97, url: 'assets/img/hat/RENO.png' },
          { id: 98, url: 'assets/img/hat/RICK.png' },
          { id: 99, url: 'assets/img/hat/SAFARI.png' },
          { id: 100, url: 'assets/img/hat/SANTA.png' },
          { id: 101, url: 'assets/img/hat/SECURITY.png' },
          { id: 102, url: 'assets/img/hat/SHERIFF.png' },
          { id: 103, url: 'assets/img/hat/SIGN.png' },
          { id: 104, url: 'assets/img/hat/SNORKEL.png' },
          { id: 105, url: 'assets/img/hat/SNOW.png' },
          { id: 106, url: 'assets/img/hat/SNOWMAN.png' },
          { id: 107, url: 'assets/img/hat/SOLDIER.png' },
          { id: 108, url: 'assets/img/hat/STICKMAN.png' },
          { id: 109, url: 'assets/img/hat/STPATRICK.png' },
          { id: 110, url: 'assets/img/hat/SUNGLASSES.png' },
          { id: 111, url: 'assets/img/hat/TOPHAT.png' },
          { id: 112, url: 'assets/img/hat/TOWEL.png' },
          { id: 113, url: 'assets/img/hat/USHANKA.png' },
          { id: 114, url: 'assets/img/hat/VIKING.png' },
          { id: 115, url: 'assets/img/hat/WHITEHAT.png' },
          { id: 116, url: 'assets/img/hat/WHITERABBIT.png' },
          { id: 117, url: 'assets/img/hat/WILDWEST.png' },
          { id: 118, url: 'assets/img/hat/WINTER.png' },
          { id: 119, url: 'assets/img/hat/WITCH.png' },
          { id: 120, url: 'assets/img/hat/WOLF.png' },
          { id: 121, url: 'assets/img/hat/WORKER.png' },
          { id: 122, url: 'assets/img/hat/XMAS.png' },
          { id: 123, url: 'assets/img/hat/ALICE.png' },
        ],
      },
      {
        id: 4,
        key: 'dress',
        url: '/assets/img/COSTUME.png',
        items: [
          { id: 1, url: 'assets/img/dress/BASE.png' },
          { id: 2, url: 'assets/img/dress/ASTRO.png' },
          { id: 3, url: 'assets/img/dress/BALLERINA.png' },
          { id: 4, url: 'assets/img/dress/BALLERINAazul.png' },
          { id: 5, url: 'assets/img/dress/BALLERINAmorada.png' },
          { id: 6, url: 'assets/img/dress/BLACKSUIT.png' },
          { id: 7, url: 'assets/img/dress/CAPTAIN.png' },
          { id: 8, url: 'assets/img/dress/DOCTOR.png' },
          { id: 9, url: 'assets/img/dress/EXPLORER.png' },
          { id: 10, url: 'assets/img/dress/HADES.png' },
          { id: 11, url: 'assets/img/dress/HEARTS.png' },
          { id: 12, url: 'assets/img/dress/HERCULES.png' },
          { id: 13, url: 'assets/img/dress/JACKET.png' },
          { id: 14, url: 'assets/img/dress/LATEX.png' },
          { id: 15, url: 'assets/img/dress/MADHATTER.png' },
          { id: 16, url: 'assets/img/dress/MECHANIC.png' },
          { id: 17, url: 'assets/img/dress/MEGARA.png' },
          { id: 18, url: 'assets/img/dress/MILITARY.png' },
          { id: 19, url: 'assets/img/dress/MINER.png' },
          { id: 20, url: 'assets/img/dress/MORTY.png' },
          { id: 21, url: 'assets/img/dress/POLICE.png' },
          { id: 22, url: 'assets/img/dress/REDQUEEN.png' },
          { id: 23, url: 'assets/img/dress/RICK.png' },
          { id: 24, url: 'assets/img/dress/SECURITY.png' },
          { id: 25, url: 'assets/img/dress/WHITERABBIT.png' },
          { id: 26, url: 'assets/img/dress/WHITESUIT.png' },
          { id: 27, url: 'assets/img/dress/WINTER.png' },
          { id: 28, url: 'assets/img/dress/WORKER.png' },
          { id: 29, url: 'assets/img/dress/ALICE.png' },
        ],
      },
      {
        id: 5,
        key: 'pet',
        url: '/assets/img/PET.png',
        items: [
          { id: 1, url: 'assets/img/pet/BASE.png' },
          { id: 2, url: 'assets/img/pet/BEDCRAB2.png' },
          { id: 3, url: 'assets/img/pet/BRAINSLUG.png' },
          { id: 4, url: 'assets/img/pet/DOG.png' },
          { id: 5, url: 'assets/img/pet/HAMSTER.png' },
          { id: 6, url: 'assets/img/pet/MINI.png' },
          { id: 7, url: 'assets/img/pet/MINI10.png' },
          { id: 8, url: 'assets/img/pet/MINI11.png' },
          { id: 9, url: 'assets/img/pet/MINI12.png' },
          { id: 10, url: 'assets/img/pet/MINI2.png' },
          { id: 11, url: 'assets/img/pet/MINI3.png' },
          { id: 12, url: 'assets/img/pet/MINI4.png' },
          { id: 13, url: 'assets/img/pet/MINI5.png' },
          { id: 14, url: 'assets/img/pet/MINI6.png' },
          { id: 15, url: 'assets/img/pet/MINI7.png' },
          { id: 16, url: 'assets/img/pet/MINI8.png' },
          { id: 17, url: 'assets/img/pet/MINI9.png' },
          { id: 18, url: 'assets/img/pet/PANICO.png' },
          { id: 19, url: 'assets/img/pet/PEGASUS.png' },
          { id: 20, url: 'assets/img/pet/PENA.png' },
          { id: 21, url: 'assets/img/pet/ROBOT.png' },
          { id: 22, url: 'assets/img/pet/STICKMAN.png' },
          { id: 23, url: 'assets/img/pet/STICKWOMAN.png' },
          { id: 24, url: 'assets/img/pet/UFO.png' },
          { id: 25, url: 'assets/img/pet/BEDCRAB.png' },
        ],
      },
    ];
  };

  getCategories = (): Category[] => {
    return this.store;
  };
}
